### ISSUE TITLE
After updating the. md file, sidebar cannot perform hot updates

### ISSUE THREAD

**Issue by 723386252** [jooy2/vitepress-sidebar#127] opened 2024-01-31 16:27 UTC

**Comment by jooy2** [comment] 2024-03-12 01:58
Hello, thank you for using `vitepress-sidebar`.
I've seen the issue reproduce, but it's likely a setting issue with `vitepress` or `vite`.

Until the issue is resolved, you can update your `vitepress-sidebar` settings by editing the contents of the file or folder and updating it.

I'm closing the issue as it's not related to this module, but i'll keep an eye on the situation.

Regards,

**Closed by jooy2** 2024-03-12 01:58 UTC
Labels: bug
