### ISSUE TITLE
When a file or folder with the same name exists in the `documentRootPath` directory, there is a problem with the `link` of the generated result.  

### ISSUE THREAD

**Issue by liuchenzyi** [jooy2/vitepress-sidebar#186] opened 2024-12-05 15:51 UTC
Thank you for developing this plugin. I found an issue while using it:

The directory structure is as follows:
```
├───docs
│   │   api-examples.md
│   │   markdown-examples.md
│   │   website.md
│   │
│   ├───.vitepress
│   │   │   config.mts
│   │   ├───theme
│   │   │       index.ts
│   │
│   ├───docs
│   │       index.md
│   │       VitePress.md
```
The configuration is as follows:
```
const vitePressSidebarOptions = {
	documentRootPath: '/docs',
	collapsed: false,
	capitalizeFirst: true,
	debugPrint: true,
	useTitleFromFrontmatter: true,
	excludeFilesByFrontmatterFieldName: "exclude",
	useFolderLinkFromIndexFile: true,
};
```
The generated structure is:
```
[
	{
		"text": "Api-examples",
		"link": "/api-examples"
	},
	{
		"text": "Docs",
		"link": "/docs/index.md",
		"items": [
			{
				"text": "VitePress",
				"link": "/VitePress"
			}
		],
	},
	{
		"text": "Markdown-examples",
		"link": "/markdown-examples"
	}
]
```
I traced the issue and found it in the following code:
![image](https://github.com/user-attachments/assets/ce9d66e1-31c6-463c-8bca-7caa9cc576a7)
Should the logic in this part of the code be modified?

**Comment by jooy2** [comment] 2024-12-05 23:24
Hello! Thank you for using `vitepress-sidebar`.

If I understand correctly, the path `/docs` in the first step does not show up in the sidebar results? Normally, the path in `documentRootPath` is treated as the root path of the document and does not show up in the sidebar results.

If not, can you be a little more specific about what you're seeing, and what part of the code you've shown is believed to be wrong?

**Comment by jooy2** [comment] 2024-12-06 01:08
Hello, thank you for using `vitepress-sidebar`.

I just checked the issue again after I commented and realized your issue.

I'll comment again once I've fixed it, thank you.

**Comment by jooy2** [comment] 2024-12-06 04:50
Hello! Thank you for your patience.

Your case was one that I hadn't considered, which is why I was slow to spot the issue. I'll be sure to look for it in more situations in the future. Thank you for reporting the issue!

This issue has been fixed and released in version `1.29.1`. Could you please upgrade to that version and check if the issue is resolved?

Regards,

**Comment by liuchenzyi** [comment] 2024-12-06 05:17
I updated the version and verified that the problem has been solved, thank you!
I apologize for the distress caused by this as the description I provided earlier may not have been clear enough.

**Comment by jooy2** [comment] 2024-12-06 05:27
No problem, the title and screenshot gave me a quick clue :)

I'm closing this issue, but if you have any new problems in the future, feel free to create a new issue!

Regards,

**Closed by jooy2** 2024-12-06 05:27 UTC
Labels: bug
